### PR TITLE
randexp: Convert string to regexp

### LINKED ISSUE #49: Cannot create property '_randexp' on string
Hi,
looks like there is a bug in https://github.com/fent/randexp.js/blob/master/lib/randexp.js#L241.
If you pass a string and not a RegExp as `regexp`, setting that property does not work.

Cheers,
Max

### PR DESCRIPTION
**Pull request by maximilian-krauss**
Fixes #49

### CODE REVIEW

File: lib/randexp.js [hunk 1]
```diff
@@ -236,12 +236,16 @@ module.exports = class RandExp {
    */
   static randexp(regexp, m) {
     var randexp;
-    if (regexp._randexp === undefined) {
-      randexp = new RandExp(regexp, m);
-      regexp._randexp = randexp;
+    var regex = regexp instanceof RegExp
```
Comment (fent) [inline lib/randexp.js]: I feel like this diff would look cleaner if this line overwrite the variable `regexp`, instead of creating a new one.

Comment (maximilian-krauss) [reply lib/randexp.js]: Done 🙂

**Comment by fent** [comment]
Thank you!
